// ==========================================================
// POLITECNICA ASBANC - CONSTANTES OFICIALES ASBANC V47
// ==========================================================

export const ASBANC_RESPONSE_CODES = {
  OK: '00',
  OUT_OF_HOURS: '05',
  AFFILIATION_NOT_FOUND: '13',
  AFFILIATION_INACTIVE: '14',
  CUSTOMER_NOT_FOUND: '16',
  DEBT_NOT_FOUND: '19',
  DEBT_ALREADY_PAID: '20',
  BELOW_MINIMUM_AMOUNT: '21',
  CUSTOMER_NO_DEBTS: '22',
  NOT_ALLOWED_BY_COMPANY: '23',
  INVALID_PAYMENT_AMOUNT: '25',
  ORIGINAL_TXN_NOT_FOUND: '68',
  AMOUNT_LESS_THAN_TOTAL: '70',
  DUPLICATE_TRACE: '71',
  REVERSAL_TIMEOUT_EXCEEDED: '72',
  PAYMENT_MUST_BE_TOTAL: '74',
  PAY_OLDER_DEBTS_FIRST: '75',
  INVALID_CURRENCY: '81',
  INVALID_BANK_CODE: '82',
  UNKNOWN_ERROR: '99',
} as const;

export const ASBANC_RESPONSE_DESCRIPTIONS: Record<string, string> = {
  '00': 'OK',
  '05': 'FUERA DE HORARIO DE ATENCION',
  '13': 'AFIL. EMPR.-SERVICIO NO EXISTE',
  '14': 'AFIL. EMPR.-SERVICIO NO ACTIVO',
  '16': 'CLIENTE NO EXISTE',
  '19': 'CUOTA PAGADA NO EXISTE',
  '20': 'CUOTA PAGADA YA CANCELADA',
  '21': 'NO CUMPLE IMPORTE MINIMO',
  '22': 'CLIENTE SIN DEUDAS PENDIENTES',
  '23': 'NO PROCEDE X IND. EMPRESA',
  '25': 'MONTO DE PAGO INVALIDO',
  '68': 'TXN ORIG. A ANULAR NO EXISTE',
  '70': 'IMP. PAGADO MENOR PAGO TOTAL',
  '71': 'TRACE DUPLICADO X FECHA/CANAL',
  '72': 'TIEMPO EXTORNO/ANULA. EXCEDIDO',
  '74': 'EL PAGO DEBE SER TOTAL',
  '75': 'PAGAR ANTES CTAS. ANTERIORES',
  '81': 'MONEDA DE PAGO INVALIDO',
  '82': 'CODIGO DE BANCO INVALIDO',
  '99': 'ERROR DESCONOCIDO',
};

export const ASBANC_BANKS = {
  BCP: '1020',
  BANBIF: '1021',
  INTERBANK: '1022',
  BBVA: '1023',
  SCOTIABANK: '1024',
  COMERCIO: '1026',
} as const;

export const ASBANC_CHANNELS = {
  VENTANILLA: '10',
  ATM: '20',
  AGENTE: '30',
  KIOSKO: '50',
  INTERNET_BANKING: '60',
  IVR: '70',
  BANCA_CELULAR: '80',
  YAPE: '81',
  PLIN: '82',
  OTROS: '99',
} as const;

export const ASBANC_QUERY_TYPES = {
  CODIGO_CLIENTE: '0',
  DNI: '1',
  RUC: '2',
} as const;

export const ASBANC_PAYMENT_METHODS = {
  EFECTIVO: '01',
  DEBITO: '02',
  CREDITO: '03',
  CHEQUE_MISMO_BANCO: '04',
  TARJETA_VIRTUAL: '05',
  CARGO_EN_CUENTA: '06',
  CARGO_Y_EFECTIVO: '07',
  CHEQUE_OTRO_BANCO: '08',
} as const;

export const ASBANC_CURRENCIES = {
  PEN: '1', // Soles
  USD: '2', // Dólares
} as const;
